{{- define "global.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "global.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "global.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "common.labels" -}}
app: {{ include "global.name" . }}
helm.sh/chart: {{ include "global.chart" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end }}

{{- define "common.selectorLabels" -}}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}


{{/*
Returns a secret's value if it already exists in Kubernetes.
*/}}
{{- define "getSecretValue" }}
{{- $obj := (lookup "v1" .Kind .Namespace .Name).data -}}
{{- if $obj }}
{{- index $obj .Key -}}
{{- end -}}
{{- end }}



{{/* BACKEND */}}

{{- define "backend.fullname" -}}
{{ template "global.fullname" . }}
{{- end -}}

{{- define "backend.selectorLabels" -}}
app.kubernetes.io/name: {{ include "backend.fullname" . }}
{{ include "common.selectorLabels" . }}
{{- end -}}

{{- define "backend.labels" -}}
{{ include "common.labels" . }}
{{ include "backend.selectorLabels" . }}
{{- end -}}


{{/*
Return the secret name containing MongoDB custom-user credentials.
Defaults to the secret auto-generated by the CloudPirates mongodb subchart.
Set mongodb.customUser.existingSecret to supply your own secret instead.
*/}}
{{- define "backend.databaseSecretName" -}}
{{- coalesce .Values.mongodb.customUser.existingSecret (printf "%s-mongodb-custom-user-secret" .Release.Name | trunc 63 | trimSuffix "-") -}}
{{- end }}


{{/* MONGODB CONNECTION HELPERS */}}

{{/*
Selector labels that match MongoDB pods created by the CloudPirates subchart.
Mirrors the cloudpirates.selectorLabels output for chart name "mongodb".
If mongodb.nameOverride is set, the subchart will use that as app.kubernetes.io/name.
*/}}
{{- define "mongodb.podSelectorLabels" -}}
app.kubernetes.io/name: {{ default "mongodb" .Values.mongodb.nameOverride | trunc 63 | trimSuffix "-" }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/*
Return the MongoDB service host.
Uses the headless service when replicaSet is enabled.
*/}}
{{- define "backend.mongodb.host" -}}
{{- if .Values.mongodb.replicaSet.enabled -}}
{{- printf "%s-mongodb-headless.%s.svc.cluster.local" .Release.Name .Release.Namespace -}}
{{- else -}}
{{- printf "%s-mongodb.%s.svc.cluster.local" .Release.Name .Release.Namespace -}}
{{- end -}}
{{- end -}}

{{/*
Return the MongoDB service port.
*/}}
{{- define "backend.mongodb.port" -}}
{{- .Values.mongodb.service.port | default 27017 -}}
{{- end -}}

{{/*
Return the MongoDB database name.
*/}}
{{- define "backend.mongodb.database" -}}
{{- .Values.mongodb.customUser.database -}}
{{- end -}}

{{/*
Return the MongoDB username.
*/}}
{{- define "backend.mongodb.username" -}}
{{- .Values.mongodb.customUser.name -}}
{{- end -}}

{{/*
Return non-empty if MongoDB authentication is enabled, empty otherwise.
Usage: {{- if include "backend.mongodb.authEnabled" . }}
*/}}
{{- define "backend.mongodb.authEnabled" -}}
{{- if .Values.mongodb.auth.enabled -}}
{{- true -}}
{{- end -}}
{{- end -}}
