---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "backend.fullname" . }}
          {{- with .Values.backend.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: TEST_SUITE
              value: {{ .Values.backend.testSuite | quote }}
            # PUBLISHER INFO
            - name: PUBLISHER_DOMAIN
              value: {{ .Values.backend.host }}
            - name: PUBLISHER_WITNESS_ID
              value: {{ .Values.backend.environment.publisherWitnessId | quote }}
            - name: PROJECT_TITLE
              value: {{ .Values.backend.environment.projectTitle | quote }}
            - name: PROJECT_VERSION
              value: {{ .Values.backend.environment.projectVersion | quote }}

            # WEBVH SERVER
            - name: WEBVH_SERVER_URL
              value: {{ .Values.backend.environment.webvhServerUrl | quote }}

            # TRACTION
            - name: TRACTION_API_URL
              value: {{ .Values.backend.traction.apiUrl }}
            - name: TRACTION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.tractionSecretName" . }}
                  key: {{ .Values.backend.traction.secretKeys.apiKey }}
            - name: TRACTION_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.tractionSecretName" . }}
                  key: {{ .Values.backend.traction.secretKeys.tenantId }}

            # MONGODB
            - name: MONGO_HOST
              value: {{ include "backend.mongodb.host" . | quote }}
            - name: MONGO_PORT
              value: {{ include "backend.mongodb.port" . | quote }}
            - name: MONGO_DB
              value: {{ include "backend.mongodb.database" . | quote }}
            {{- if include "backend.mongodb.authEnabled" . }}
            - name: MONGO_USER
              value: {{ include "backend.mongodb.username" . | quote }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.databaseSecretName" . }}
                  key: {{ .Values.mongodb.customUser.secretKeys.password }}
            {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.backend.service.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /server/status
              port: {{ .Values.backend.service.apiPort }}
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /server/status
              port: {{ .Values.backend.service.apiPort }}
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}