{{- if not .Values.backend.traction.existingSecret }}
{{ $secretName := include "backend.tractionSecretName" . }}
{{ $tenantKey := .Values.backend.traction.secretKeys.tenantId }}
{{ $apiKey := .Values.backend.traction.secretKeys.apiKey }}
{{ $tenantId := include "getSecretValue" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" $tenantKey) }}
{{ $apiKeyValue := include "getSecretValue" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" $apiKey) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ $secretName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ $tenantKey }}: {{ $tenantId }}
  {{ $apiKey }}: {{ $apiKeyValue }}
{{- end }}
