# generated by datamodel-codegen from UNTP v0.7.0 ConformityCredential.json
# (bundled copy under untp/bundled/; JSON `prefixItems` stripped only under `@context` for codegen — see scripts/generate_untp_pydantic_models.py)

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, Base64Str, BaseModel, ConfigDict, Field



class IssuerAlsoKnownA(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )
    registeredId: str | None = Field(
        default=None,
        description="The registration number (alphanumeric) of the Party within the register. Unique within the register.",
        examples=[90664869327],
    )


class CredentialIssuer(BaseModel):
    """
    The issuer party (person or organisation) of a verifiable credential.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["CredentialIssuer"]
    )
    id: AnyUrl = Field(
        ...,
        description="The W3C DID of the issuer - should be a did:web or did:webvh",
        examples=["did:web:identifiers.example-company.com:12345"],
    )
    name: str = Field(
        ...,
        description="The name of the issuer person or organisation",
        examples=["Example Company Pty Ltd"],
    )
    issuerAlsoKnownAs: list[IssuerAlsoKnownA] | None = Field(
        default=None,
        description="An optional list of other registered identifiers for this credential issuer ",
    )


class Type2(StrEnum):
    """
    The type of status list - must be set to "The type property MUST be BitstringStatusListEntry."
    """

    BitstringStatusListEntry = "BitstringStatusListEntry"


class StatusPurpose(StrEnum):
    """
    Status purpose drawn from a standard list but extensible as per w3c bitstring status list specification.
    """

    refresh = "refresh"
    revocation = "revocation"
    suspension = "suspension"
    message = "message"


class BitstringStatusListEntry(BaseModel):
    """
    A privacy-preserving, space-efficient, and high-performance mechanism for publishing status information such as suspension or revocation of Verifiable Credentials through use of bitstrings.  See https://www.w3.org/TR/vc-bitstring-status-list/ for full details.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type2 = Field(
        ...,
        description='The type of status list - must be set to "The type property MUST be BitstringStatusListEntry."',
        examples=["BitstringStatusListEntry"],
    )
    id: AnyUrl | None = Field(
        default=None,
        description="optional identifer of this status list entry.",
        examples=['https://example-cab.com/credentials/status/3#94567"'],
    )
    statusPurpose: StatusPurpose = Field(
        ...,
        description="Status purpose drawn from a standard list but extensible as per w3c bitstring status list specification.",
        examples=["refresh"],
    )
    statusListIndex: int = Field(
        ...,
        description="\tThe statusListIndex property MUST be an arbitrary size integer greater than or equal to 0, expressed as a string in base 10. The value identifies the position of the status of the verifiable credential.",
        examples=[94567],
        ge=0,
    )
    statusListCredential: AnyUrl = Field(
        ...,
        description="The statusListCredential property MUST be a URL to a verifiable credential. When the URL is dereferenced, the resulting verifiable credential MUST have type property that includes the BitstringStatusListCredential value.",
        examples=["https://example-cab.com/credentials/status/4"],
    )



class RenderTemplate2024(BaseModel):
    """
    A single template format focused render method where the content/media type decision becomes secondary (and is expressed separately).See https://github.com/w3c-ccg/vc-render-method/issues/9
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["RenderTemplate2024"]
    )
    name: str | None = Field(
        default=None, description="Human facing display name for selection"
    )
    mediaQuery: str | None = Field(
        default=None,
        description="Media query as defined in https://www.w3.org/TR/mediaqueries-4/",
    )
    template: str | None = Field(
        default=None,
        description="An inline template field for use cases where remote retrieval of a render method is suboptimal",
    )
    url: AnyUrl | None = Field(
        default=None, description="URL for remotely hosted template"
    )
    mediaType: str | None = Field(
        default=None, description="media type of the rendered output (eg text/html)"
    )
    digestMultibase: str | None = Field(
        default=None,
        description="Used for resource integrity and/or validation of the inline `template`",
    )


class AssessorLevel(StrEnum):
    """
    Assurance code pertaining to assessor (relation to the object under assessment)
    """

    self = "self"
    commercial = "commercial"
    buyer = "buyer"
    membership = "membership"
    unspecified = "unspecified"
    field_3rdParty = "3rdParty"
    hybrid = "hybrid"


class AssessmentLevel(StrEnum):
    """
    Assurance pertaining to assessment (any authority or support for the assessment process)
    """

    authority_benchmark = "authority-benchmark"
    authority_mandate = "authority-mandate"
    authority_globalmra = "authority-globalmra"
    authority_peer = "authority-peer"
    authority_extended_mra = "authority-extended-mra"
    scheme_self = "scheme-self"
    scheme_cab = "scheme-cab"
    no_endorsement = "no-endorsement"


class AttestationType(StrEnum):
    """
    The type of criterion (optional or mandatory).
    """

    certification = "certification"
    declaration = "declaration"
    inspection = "inspection"
    testing = "testing"
    verification = "verification"
    validation = "validation"
    calibration = "calibration"


class IssuedToParty(BaseModel):
    """
    The party to whom the conformity attestation was issued.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )
    registeredId: str | None = Field(
        default=None,
        description="The registration number (alphanumeric) of the Party within the register. Unique within the register.",
        examples=[90664869327],
    )
    description: str | None = Field(
        default=None,
        description="Description of the party including function and other names.",
    )


class ReferenceScheme(BaseModel):
    """
    The conformity scheme under which this attestation is made.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this conformity scheme. Typically represented as a URI SchemeOwner/SchemeName URI",
        examples=["https://sample-scheme.org/lrap"],
    )
    name: str = Field(
        ...,
        description="Name of this scheme as defined by the scheme owner.",
        examples=["Labour rights assessment program"],
    )


class ReferenceProfile(BaseModel):
    """
    The specific versioned conformity profile (comprising a set of versioned criteria) against which this conformity attestation is made.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this context specific conformity profile. Typically represented as a URI SchemeOwner/profileID URI",
        examples=["https://vocabulary.sample-scheme.org/profile/lrap/v1.0"],
    )
    name: str = Field(
        ...,
        description="Name of this conformity profile as defined by the scheme owner.",
        examples=["Forced labour assessment criterion"],
    )


class IssuingAuthority(BaseModel):
    """
    The competent authority that issued the accreditation.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )
    registeredId: str | None = Field(
        default=None,
        description="The registration number (alphanumeric) of the Party within the register. Unique within the register.",
        examples=[90664869327],
    )


class Image(BaseModel):
    """
    A binary image encoded as base64 text and embedded into the data.  Use this for small images like certification trust marks or regulated labels.  Large impages should be external links.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Image"]
    )
    name: str = Field(
        ...,
        description="the display name for this image",
        examples=["certification trust mark"],
    )
    description: str | None = Field(
        default=None,
        description="The detailed description / supporting information for this image.",
    )
    imageData: Base64Str = Field(
        ..., description="The image data encoded as a base64 string."
    )
    mediaType: str = Field(
        ...,
        description="The media type of this image (eg image/png)\n\n    This is an enumerated value, but the list of valid values are too big, or change too often to include here. You can access the list of allowable values at this URL:  https://mimetype.io/\n    ",
    )


class Link(BaseModel):
    """
    A structure to provide a URL link plus metadata associated with the link.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Link"]
    )
    linkURL: AnyUrl = Field(
        ...,
        description="The URL of the target resource.  ",
        examples=["https://files.example-certifier.com/1234567.json"],
    )
    linkName: str = Field(..., description="Display name for this link.")
    digestMultibase: str | None = Field(
        default=None,
        description="An optional multi-base encoded digest to ensure the content of the link has not changed. See https://www.w3.org/TR/vc-data-integrity/#resource-integrity for more information.",
        examples=["abc123-example-digest-invalid"],
    )
    mediaType: str | None = Field(
        default=None,
        description="The media type of the target resource.",
        examples=["application/ld+json"],
    )
    linkType: str | None = Field(
        default=None,
        description="The type of the target resource - drawn from a controlled vocabulary ",
        examples=["https://test.uncefact.org/vocabulary/linkTypes/dcc"],
    )


class Score(BaseModel):
    """
    A single score within a scoring framework.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Score"]
    )
    code: str = Field(..., description='The coded value for this score (eg "AAA")')
    rank: int | None = Field(
        default=None,
        description='The ranking of this score within the scoring framework - using an integer where "1" is the highest rank.',
    )
    definition: str | None = Field(
        default=None, description="A description of the meaning of this score."
    )


class AssessmentCriterion(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this conformity criterion. Typically represented as a URI SchemeOwner/CriterionID URI",
        examples=["https://vocabulary.sample-scheme.org/criterion/lb/v1.0"],
    )
    name: str = Field(
        ...,
        description="Name of this criterion as defined by the scheme owner.",
        examples=["Forced labour assessment criterion"],
    )


class AssessedOrganisation(BaseModel):
    """
    An organisation that is the subject of this assessment.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )


class ReferenceStandardItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this standard. Typically represented as a URI issuer/standard URI",
        examples=["https://sample-standards.org/A1234"],
    )
    name: str = Field(
        ..., description="Name for this standard", examples=["Labour rights standard"]
    )


class ReferenceRegulationItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this standard. Typically represented as a URI government/regulation URI",
        examples=["https://regulations.country.gov/ABC-12345"],
    )
    name: str = Field(
        ...,
        description="Name of this regulation as defined by the regulator.",
        examples=["Due Diligence Directove"],
    )


class Metric(BaseModel):
    """
    The metric (eg material emissions intensity CO2e/Kg or percentage of young workers) that is measured.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this reporting metric. ",
        examples=["https://authority.gov/schemeABC/123456789"],
    )
    name: str = Field(
        ...,
        description='A human readable name for this metric (for example "water usage per Kg of material")',
        examples=["emissions intensity"],
    )


class Measure(BaseModel):
    """
    The measure class defines a numeric measured value (eg 10) and a coded unit of measure (eg KG).  There is an optional upper and lower tolerance which can be used to specify uncertainty in the measure.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Measure"]
    )
    value: float = Field(
        ..., description="The numeric value of the measure", examples=[10]
    )
    upperTolerance: float | None = Field(
        default=None,
        description="The upper tolerance associated with this measure expressed in the same units as the measure.  For example value=10, upperTolerance=0.1, unit=KGM would mean that this measure is 10kg + 0.1kg",
    )
    lowerTolerance: float | None = Field(
        default=None,
        description="The lower tolerance associated with this measure expressed in the same units as the measure.  For example value=10, lowerTolerance=0.1, unit=KGM would mean that this measure is 10kg - 0.1kg",
    )
    unit: str = Field(
        ...,
        description="Unit of measure drawn from the UNECE Rec20 measure code list.\n\n    This is an enumerated value, but the list of valid values are too big, or change too often to include here. You can access the list of allowable values at this URL:  https://vocabulary.uncefact.org/UnitMeasureCode#\n    ",
    )


class Product(BaseModel):
    """
    The product, serial or batch that is the subject of this assessment
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this product. Typically represented as a URI identifierScheme/Identifier URI or, if self-issued, as a did.",
        examples=["did:web:manufacturer.com:product:123456789"],
    )
    name: str = Field(
        ...,
        description="The product name as known to the market.",
        examples=["600 Ah Lithium Battery"],
    )
    modelNumber: str | None = Field(
        default=None,
        description="Where available, the model number (for manufactured products) or material identification (for bulk materials)",
    )
    batchNumber: str | None = Field(
        default=None,
        description="Identifier of the specific production batch of the product.  Unique within the product class.",
        examples=[6789],
    )
    itemNumber: str | None = Field(
        default=None,
        description="A number or code representing a specific serialised item of the product. Unique within product class.",
        examples=[12345678],
    )


class ProductVerification(BaseModel):
    """
    The product which is the subject of this conformity assessment
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["ProductVerification"]
    )
    product: Product = Field(
        ...,
        description="The product, serial or batch that is the subject of this assessment",
    )
    idVerifiedByCAB: bool | None = Field(
        default=None,
        description="Indicates whether the conformity assessment body has verified the identity product that is the subject of the assessment.",
    )


class Facility(BaseModel):
    """
    The facility which is the subject of this assessment
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this facility. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-location-register.com/987654321"],
    )
    name: str = Field(
        ...,
        description="Name of this facility as defined the location register.",
        examples=["Sample Factory A"],
    )
    registeredId: str | None = Field(
        default=None,
        description="The registration number (alphanumeric) of the facility within the identifier scheme. Unique within the register.",
        examples=[1234567],
    )


class FacilityVerification(BaseModel):
    """
    The facility which is the subject of this conformity assessment
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["FacilityVerification"]
    )
    facility: Facility = Field(
        ..., description="The facility which is the subject of this assessment"
    )
    idVerifiedByCAB: bool | None = Field(
        default=None,
        description="Indicates whether the conformity assessment body has verified the identity of the facility which is the subject of the assessment.",
    )


class ConformityTopic(BaseModel):
    """
    The UNTP standard classification scheme for conformity topic.  see http://vocabulary.uncefact.org/ConformityTopic
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["ConformityTopic"]
    )
    id: AnyUrl = Field(
        ..., description="The unique identifier for this conformity topic"
    )
    name: str = Field(
        ...,
        description="The human readable name for this conformity topic.",
        examples=["forced-labour"],
    )
    definition: str | None = Field(
        default=None, description="The rich definition of this conformity topic."
    )


class Endorsement(BaseModel):
    """
    The authority under which a conformity claim is issued.  For example a national accreditation authority may authorise a test lab to issue test certificates about a product against a standard.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Endorsement"]
    )
    name: str = Field(
        ...,
        description="The name of the accreditation.",
        examples=[
            "Accreditation of certifiers.com under the Australian National Greenhouse and Energy Reporting scheme (NGER)."
        ],
    )
    trustmark: Image | None = Field(
        default=None,
        description="The trust mark image awarded by the AB to the CAB to indicate accreditation.",
    )
    issuingAuthority: IssuingAuthority = Field(
        ..., description="The competent authority that issued the accreditation."
    )
    endorsementEvidence: Link | None = Field(
        default=None,
        description="The evidence that supports the authority under which the attestation is issued - for an example an accreditation certificate.",
    )


class Performance(BaseModel):
    """
    A claimed, assessed, or required performance level defined either by a scoring system or a numeric measure.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["Performance"]
    )
    metric: Metric = Field(
        ...,
        description="The metric (eg material emissions intensity CO2e/Kg or percentage of young workers) that is measured.",
    )
    measure: Measure | None = Field(
        default=None, description="The measured performance value"
    )
    score: Score | None = Field(
        default=None,
        description='A performance score (eg "AA") drawn from a scoring framework defined by the scheme or criterion.',
    )


class ConformityAssessment(BaseModel):
    """
    A specific assessment about the product or facility against a specific specification.  Eg the carbon intensity of a given product or batch.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["ConformityAssessment"]
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this assessment. Typically represented as a URI AssessmentBody/Assessment URI or a UUID",
        examples=[
            "https://sample-cab.com/assessment/e78dab5d-b6f6-4bc4-a458-7feb039f6cb3"
        ],
    )
    name: str = Field(
        ...,
        description="Name of this assessment - typically similar or the same as the referenced criterion name.",
        examples=["Sample Scheme Forced Labour Assessment"],
    )
    description: str | None = Field(
        default=None, description="Description of this conformity assessment "
    )
    assessmentCriteria: list[AssessmentCriterion] = Field(
        ..., description="The specification against which the assessment is made."
    )
    assessmentDate: date = Field(
        ...,
        description="The date on which this assessment was made. ",
        examples=["2024-03-15"],
    )
    assessedPerformance: list[Performance] = Field(
        ..., description="The assessed performance against criteria."
    )
    assessedProduct: list[ProductVerification] | None = Field(
        default=None, description="The product which is the subject of this assessment."
    )
    assessedFacility: list[FacilityVerification] | None = Field(
        default=None,
        description="The facility which is the subject of this assessment.",
    )
    assessedOrganisation: AssessedOrganisation | None = Field(
        default=None,
        description="An organisation that is the subject of this assessment.",
    )
    referenceStandard: list[ReferenceStandardItem] | None = Field(
        default=None,
        description="The reference to the standard that defines the specification / criteria",
    )
    referenceRegulation: list[ReferenceRegulationItem] | None = Field(
        default=None,
        description="The reference to the regulation that defines the assessment criteria",
    )
    specifiedCondition: list[str] | None = Field(
        default=None,
        description="A list of specific conditions that constrain this conformity assessment. For example a specific jurisdiction, material type, or test method.",
    )
    evidence: list[Link] | None = Field(
        default=None, description="Evidence to support this specific assessment."
    )
    conformityTopic: list[ConformityTopic] = Field(
        ...,
        description="The UNTP conformity topic used to categorise this assessment. Should match the topic defined by the scheme criterion.",
    )
    conformance: bool | None = Field(
        default=None,
        description="An indicator (true / false) whether the outcome of this assessment is conformant to the requirements defined by the standard or criterion.",
    )


class ConformityAttestation(BaseModel):
    """
    A conformity attestation issued by a competent body that defines one or more assessments (eg carbon intensity) about a product (eg battery) against a specification (eg LCA method) defined in a standard or regulation.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: ["ConformityAttestation"]
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this attestation. Typically represented as a URI AssessmentBody/CertificateID URI or a UUID",
        examples=["https://sample-cab.com/attestation/LR-98765"],
    )
    name: str = Field(
        ...,
        description="Name of this attestation - typically the title of the certificate.",
        examples=["Forced Labour Facility Certificate"],
    )
    description: str | None = Field(
        default=None, description="Description of this attestation."
    )
    assessorLevel: AssessorLevel = Field(
        ...,
        description="Assurance code pertaining to assessor (relation to the object under assessment)",
        examples=["self"],
    )
    assessmentLevel: AssessmentLevel = Field(
        ...,
        description="Assurance pertaining to assessment (any authority or support for the assessment process)",
        examples=["authority-benchmark"],
    )
    attestationType: AttestationType = Field(
        ...,
        description="The type of criterion (optional or mandatory).",
        examples=["certification"],
    )
    issuedToParty: IssuedToParty = Field(
        ..., description="The party to whom the conformity attestation was issued."
    )
    authorisation: list[Endorsement] | None = Field(
        default=None,
        description="The authority under which a conformity claim is issued.  For example a national accreditation authority may authorise a test lab to issue test certificates about a product against a standard.  ",
    )
    referenceScheme: ReferenceScheme = Field(
        ..., description="The conformity scheme under which this attestation is made."
    )
    referenceProfile: ReferenceProfile | None = Field(
        default=None,
        description="The specific versioned conformity profile (comprising a set of versioned criteria) against which this conformity attestation is made.",
    )
    profileScore: Score | None = Field(
        default=None,
        description="The overall performance against a scheme level performance measurement framework for the referenced profile or scheme.",
    )
    conformityCertificate: Link | None = Field(
        default=None,
        description="A reference to the human / printable version of this conformity attestation - typically represented as a PDF document. The document may have more details than are represented in the digital attestation.",
    )
    auditableEvidence: Link | None = Field(
        default=None,
        description="Auditable evidence supporting this assessment such as raw measurements, supporting documents. This is usually private data and would normally be encrypted.",
    )
    trustMark: Image | None = Field(
        default=None,
        description="A trust mark as a small binary image encoded as base64 with a description.  Maye be displayed on the conformity credential rendering.",
    )
    conformityAssessment: list[ConformityAssessment] | None = Field(
        default=None,
        description="A list of individual assessment made under this attestation. ",
    )


class DigitalConformityCredential(BaseModel):
    """
    A Digital Conformity Credential (DCC) credential.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | None = Field(
        default_factory=lambda: [
            "DigitalConformityCredential",
            "VerifiableCredential",
        ]
    )
    field_context: list[str] | None = Field(
        default=[
            "https://www.w3.org/ns/credentials/v2",
            "https://vocabulary.uncefact.org/untp/0.7.0/context/",
        ],
        alias="@context",
        description="A list of JSON-LD context URIs that define the semantic meaning of properties within the credential. ",
        examples=[
            [
                "https://www.w3.org/ns/credentials/v2",
                "https://vocabulary.uncefact.org/untp/0.7.0/context/",
            ]
        ],
        min_length=2,
    )
    id: AnyUrl = Field(
        ...,
        description="A unique identifier (URI) assigned to this verifiable credential.",
        examples=[
            "https://example-company.com/credentials/2a423366-a0d6-4855-ba65-2e0c926d09b0"
        ],
    )
    issuer: CredentialIssuer = Field(
        ...,
        description='The organisation that is the issuer of this VC. Note that the "id" property MUST be a W3C DID.  Other identifiers such as tax registration numbers can be listed in the "otherIdentifiers" property.',
    )
    validFrom: AwareDatetime = Field(
        ...,
        description="The date and time from which the credential is valid.",
        examples=["2024-03-15T12:00:00Z"],
    )
    validUntil: AwareDatetime | None = Field(
        default=None,
        description="The expiry date (if applicable) of this verifiable credential.",
        examples=["2034-03-15T12:00:00Z"],
    )
    name: str = Field(
        ...,
        description="Name of this verifiable credential instance (eg the title of a digital product passport, facility record, lifecycle event, or conformity credential)",
        examples=["Some name"],
    )
    credentialStatus: BitstringStatusListEntry | None = Field(
        default=None,
        description="A W3C VCDM2.0 compliant object containing credential status information.",
    )
    renderTemplate2024: RenderTemplate2024 | None = Field(
        default=None, description="Human rendering information for this credential."
    )
    credentialSubject: ConformityAttestation = Field(
        ...,
        description="The attestation that is the subject of this digital conformity credential.",
    )
